### ISSUE TITLE
Feature Propousal: Integrate Greenkeeper & Semantic-Release

### ISSUE THREAD

**Issue by bartekus** [opencredo/opencredo-react-boilerplate#50]
I believe that OpenCredo has a lot to gain by adapting Greenkeeper/Semantic-Release combo (they complement each-other very well) and allow for more streamlined package maintenance as well as increase confidence and clarity in versioning. 
I see OC as having the potential to become a standard by adherence to quality as one of its core principle.

The following will give you all the information.
[The Greenkeeper Workflow](http://greenkeeper.io/)
[semantic-release](https://github.com/semantic-release/semantic-release)

Given OC's is open source nature, I see no reason against this - another great feature.

**Comment by vincemtnz** [comment]
Hi @Bartekus, so I think it's a good idea, but it comes with a "but"... I'll expand each point:

Regarding Greenkeeper, I think it'd be a yes when maintaining a library. The main issue at the moment with integrating greenkeeper in this boilerplate is that there's no real test coverage, hence major upgrades wouldn't really cause builds to fail - even if the boilerplate breaks. I do feel like it's a good approach for a real life project scenario, provided there is good test coverage (perhaps even adding a check so that the codebase's test coverage is above a certian %). In the context of this boilerplate, however, it might be counter productive.

As for semantic versioning, we're going to try to adhere to a stricter versioning once we're happy with it, even if just for informative purposes. 

(Closing the issue, but we can keep the conversation open :+1: )

**Comment by bartekus** [comment]
Excellent reasoning, and definitely not something I even considered yet it is so true! 
Thank you once more for taking the time to explain this as I'm still fairly naive and inexperienced to see the full picture but I'm trying to become more mindful of such things.

Perhaps instead of proposing new features I'll better serve this project by focusing on test-creation; certainly I could use more practice in that department and it would also probably allow you a more breathing room in the development front.
